FROM golang:latest AS build-env
WORKDIR /src
ENV CGO_ENABLED=0
COPY go.* .
RUN go mod download
COPY *.go .
RUN go build -a -o zwiebelproxy -ldflags="-s -w" -trimpath

FROM alpine:latest
RUN mkdir -p /app \
  && adduser -D zwiebel \
  && chown -R zwiebel:zwiebel /app
COPY --from=build-env /src/zwiebelproxy /app/zwiebelproxy
USER zwiebel
ENTRYPOINT [ "/app/zwiebelproxy" ]
