// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(err string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Zwiebelproxy</title><style>\n    *, *::before, *::after {\n      box-sizing: border-box;\n      font-family: Gotham Rounded, sans-serif;\n      font-weight: normal;\n    }\n    a {\n      color: #bc6575;\n    }\n    a:link { text-decoration: none; }\n    a:visited { text-decoration: none; }\n    a:hover { text-decoration: underline; }\n\n    body {\n      padding: 0;\n      margin: 0;\n      background-color: #1A1A1D;\n      color: #C3073f;\n    }\n    .container {\n      display: flex;\n      align-items: center;\n      text-align: center;\n      justify-content: center;\n      flex-direction: column;\n      height: 100vh;\n    }\n    h1   {\n      font-weight: bolder;\n      font-size: 10vw;\n    }\n    h5    {\n      font-weight: bolder;\n      font-size: 1vw;\n    }\n    .error {\n      border: 10px solid black;\n      min-width: 80%;\n      padding: 2vh;\n      background-color: #C3073f;\n      color: black;\n      font-weight: bold;\n      font-size: 2em;\n    }\n  </style></head><body><div class=\"container\"><h1>ZWIEBELPROXY</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if err != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"error\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(err)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/server/templates/default.templ`, Line: 62, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<h5>&copy; by <a href=\"https://firefart.at\" target=\"_blank\">firefart</a></h5><h5>Source code available under <a href=\"https://github.com/firefart/zwiebelproxy\" target=\"_blank\">https://github.com/firefart/zwiebelproxy</a></h5></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
