name: Build Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_docker_images:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker zwiebel meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: firefart/zwiebelproxy
          tags: |
            # set latest tag for default branch
            type=raw,value=zwiebelproxy-latest,enable={{is_default_branch}}
            # make a sha tag
            type=sha,enable=true,priority=100,prefix=zwiebelproxy-sha-,suffix=,format=short
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=zwiebelproxy-nightly-

      - name: Docker tor meta
        id: meta_tor
        uses: docker/metadata-action@v5
        with:
          images: firefart/zwiebelproxy
          tags: |
            # set latest tag for default branch
            type=raw,value=tor-latest,enable={{is_default_branch}}
            # make a sha tag
            type=sha,enable=true,priority=100,prefix=tor-sha-,suffix=,format=short
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=tor-nightly-

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push zwiebelproxy
        uses: docker/build-push-action@v6
        with:
          file: Dockerfiles/Dockerfile.zwiebelproxy
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push tor
        uses: docker/build-push-action@v6
        with:
          file: Dockerfiles/Dockerfile.tor
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le
          tags: ${{ steps.meta_tor.outputs.tags }}
          labels: ${{ steps.meta_tor.outputs.labels }}
